import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

import { Inter } from 'next/font/google'; 

const font = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


import Sidebar from '../components/Sidebar'

export default function RootLayout({
  children,}: {
    children:React.ReactNode
  
}) {
  return (
    <html lang="en">
      <body className={font.classname}>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  )
}